
// import type { Metadata } from "next";
// import "./globals.css";
// import Header from "@/components/globalComponents/header/page";
// import Footer from "@/components/globalComponents/footer/page";
// import ClientLayout from "@/components/reduxProvider/reduxProvider"; 
// import {
//   ClerkProvider,
//   SignInButton,
//   SignedIn,
//   SignedOut,
//   UserButton
// } from '@clerk/nextjs'
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
    
//     <html lang="en">
//       <ClientLayout> 
//         <body>
//           <Header />
//           {children}
//           <Footer />
//         </body>
//       </ClientLayout>
//     </html>
//   );
// }


import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/globalComponents/header/page";
import Footer from "@/components/globalComponents/footer/page";
import ClientLayout from "@/components/reduxProvider/reduxProvider"; 
import { ClerkProvider } from '@clerk/nextjs';
import AuthProvider from "./provider";
import LoaderWrapper from "@/components/globalComponents/loaderWrapper";

// Set metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <ClientLayout>
            <Header />
            <LoaderWrapper>{children}</LoaderWrapper>
          </ClientLayout>
        </body>
      </html>
      </AuthProvider>
   
  );
}
